95645284-6d1c-4d7e-9769-f70e0c37a971


name: ArmorCode

env:
  armorcodehost: https://app.armorcode.com
  product: DVWA
  subProduct: DVWAmono
  environment: Production
  token: ${{secrets.ARMORCODE_TOKEN}}
  buildTool: GITHUB_ACTIONS
  buildNumber: 95645284-6d1c-4d7e-9769-f70e0c37a971
  end: 30
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://app.armorcode.com/static/scripts/slastatus.sh
          sh slastatus.sh
